name: Smart App CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm install

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy frontend to nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r frontend/dist/* /var/www/html/

      - name: Restart backend with PM2
        run: |
          pm2 delete smart || true
          pm2 start npm --name "smart" -- start
          pm2 save